Fix: docker container not removed when jest tests fail, or when scilla type check script fails
Zilliqa/ZRC pull request #123
Opened 2021-12-05 11:42 UTC by gb3h

Small QOL improvement for those forking this repoing and running tests frequently.
Links to issue #122 

Simple fix makes the bash cleanup lines run even in the event of failure.

2021-12-06 04:09 UTC, noel-yoo approved these changes
LGTM

2021-12-06 10:43 UTC, noel-yoo requested changes

2021-12-06 10:43 UTC, noel-yoo commented on ci_scilla_type_check.sh
> +quit 0
@gb3h Can you add a new line?

2021-12-06 10:52 UTC, gb3h commented on ci_scilla_type_check.sh
> +quit 0
Done 👍

2021-12-06 14:30 UTC, noel-yoo approved these changes
LGTM

2021-12-09 11:11 UTC, bb111189 approved these changes

2021-12-09 11:11 UTC, merged